import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const blog = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    author: z.string().default('The Pro Git project'),
    /** True when the post was generated by an AI agent rather than written by a human. */
    automated: z.boolean().default(false),
  }),
});

export const collections = { blog };
